#ifndef LUACPPB_CONFIG_H_
#define LUACPPB_CONFIG_H_

// #define LUACPPB_CXX_MODE
// #define LUACPPB_NO_EXCEPTION_PROPAGATION
// #define LUACPPB_NO_ERROR_SUPPORT
// #define LUACPPB_NO_EXCEPTION_PROPAGATION

#endif